[versions]
agp = "9.2.1"
libxposed = "102.0.0"
dexkit = "2.2.0"
junit = "4.13.2"

[libraries]
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "libxposed" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
